/*
 * SPDX-FileCopyrightText: 2025 kaumei.io
 * SPDX-License-Identifier: Apache-2.0
 */

package io.kaumei.jdbc.docs;

import io.kaumei.jdbc.annotation.JdbcName;
import io.kaumei.jdbc.annotation.JdbcSelect;
import io.kaumei.jdbc.annotation.JdbcToJava;
import io.kaumei.jdbc.annotation.JdbcUpdate;
import io.kaumei.jdbc.annotation.config.JdbcReturnGeneratedValues;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Stream;

// @part:class
public interface SimpleExample {

    // @part:PricingPlan
    enum PricingPlan {
        FREE, BASIC, PRO, ENTERPRISE
    }
    // @part:PricingPlan

    /**
     * A record which will hold one row of the table.
     */
    // @part:CustomerAsRecord
    record CustomerAsRecord(long id,
                            String name,
                            @Nullable Integer budge,
                            @JdbcName("pricing_plan") @NonNull PricingPlan plan,
                            @JdbcName("created_at") LocalDateTime created) {
    }
    // @part:CustomerAsRecord


    /**
     * A class which can also hold one row of the table.
     */
    // @part:CustomerAsClass
    class CustomerAsClass {
        private final long id;
        private final String name;
        private final @Nullable Integer budge;
        private final @NonNull PricingPlan plan;
        private final LocalDateTime created;

        CustomerAsClass(long id,
                        String name,
                        @Nullable Integer budge,
                        @JdbcName("pricing_plan") @NonNull PricingPlan plan,
                        @JdbcName("created_at") LocalDateTime created) {
            this.id = id;
            this.name = name;
            this.budge = budge;
            this.plan = plan;
            this.created = created;
        }

        // ...
        // @part:CustomerAsClass
        public long getId() {
            return this.id;
        }

        public String getName() {
            return this.name;
        }

        public @Nullable Integer getBudge() {
            return this.budge;
        }

        public @NonNull PricingPlan getPlan() {
            return this.plan;
        }

        public LocalDateTime getCreated() {
            return this.created;
        }
        // @part:CustomerAsClass
    }
    // @part:CustomerAsClass

    // @part:LocalDateTime
    @JdbcToJava
    static LocalDateTime fromDB(java.sql.Timestamp ts) {
        return ts.toLocalDateTime();
    }
    // @part:LocalDateTime

    /*
     * @return a list of all rows of the table.
     */
    // @part:select
    @JdbcSelect("SELECT * FROM db_customers ORDER BY name")
    List<CustomerAsRecord> listCustomers();
    // @part:select

    /*
     * @return a stream of all rows of the table.
     */
    // @part:select
    @JdbcSelect("SELECT * FROM db_customers ORDER BY name")
    Stream<CustomerAsClass> streamCustomers();
    // @part:select

    /**
     * The database generated values.
     */
    // @part:Gen
    record CustomerGen(long id, @JdbcName("created_at") LocalDateTime createdDateTime) {
    }
    // @part:Gen

    /*
     * Define a SQL update to insert a row into the table.
     * The values of the 'id' and 'created' columns will be generated by the database.
     * To get those values back we define a record CustomerGen and add the @JdbcReturnGeneratedValues annotation
     */
    // @part:insert
    @JdbcUpdate("INSERT INTO db_customers (name, budge, pricing_plan) VALUES (:name, :budge, :plan)")
    @JdbcReturnGeneratedValues
    CustomerGen insertCustomer(String name, @Nullable Integer budge, @NonNull PricingPlan plan);
    // @part:insert

    /*
     * @return the number of delete rows (return value of executeUpdate)
     */
    // @part:delete
    @JdbcUpdate("DELETE FROM db_customers")
    int deleteCustomers();
    // @part:delete

    /*
     * @return the count(*) of all customers
     */
    // @part:countCustomers
    @JdbcSelect("SELECT COUNT(*) FROM db_customers")
    int countCustomers();
    // @part:countCustomers
}
// @part:class
