/*
 * SPDX-FileCopyrightText: 2025 kaumei.io
 * SPDX-License-Identifier: Apache-2.0
 */

package io.kaumei.jdbc.docs;

import io.kaumei.jdbc.annotation.JdbcName;
import io.kaumei.jdbc.annotation.JdbcSelect;
import io.kaumei.jdbc.annotation.JdbcToJava;
import io.kaumei.jdbc.annotation.JdbcUpdate;
import io.kaumei.jdbc.annotation.config.JdbcReturnGeneratedValues;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Stream;

// @part:class
public interface SimpleExample {

    /**
     * A record which will hold one row of the table.
     */
    // @part:CustomerAsRecord
    record CustomerAsRecord(long id,
                            @JdbcName("name") String firstName,
                            @org.jspecify.annotations.Nullable Integer budge,
                            LocalDateTime created) {
    }
    // @part:CustomerAsRecord

    /**
     * A class which can also hold one row of the table.
     */
    // @part:CustomerAsClass
    class CustomerAsClass {
        private final long id;
        private final String firstName;
        private final @org.jspecify.annotations.Nullable Integer budge;
        private final LocalDateTime created;

        CustomerAsClass(long id,
                        @JdbcName("name") String firstName,
                        @org.jspecify.annotations.Nullable Integer budge,
                        LocalDateTime created) {
            this.id = id;
            this.firstName = firstName;
            this.budge = budge;
            this.created = created;
        }
        // ...
        // @part:CustomerAsClass

        public long getId() {
            return this.id;
        }

        public String getFirstName() {
            return this.firstName;
        }

        public @org.jspecify.annotations.Nullable Integer getBudge() {
            return this.budge;
        }

        public LocalDateTime getCreated() {
            return this.created;
        }
        // @part:CustomerAsClass
    }
    // @part:CustomerAsClass

    // @part:LocalDateTime
    @JdbcToJava
    static LocalDateTime fromDB(java.sql.Timestamp ts) {
        return ts.toLocalDateTime();
    }
    // @part:LocalDateTime

    /*
     * @return a list of all rows of the table.
     */
    // @part:select
    @JdbcSelect("SELECT * FROM db_customers ORDER BY name")
    List<CustomerAsRecord> listCustomers();
    // @part:select

    /*
     * @return a stream of all rows of the table.
     */
    // @part:select
    @JdbcSelect("SELECT * FROM db_customers ORDER BY name")
    Stream<CustomerAsClass> streamCustomers();
    // @part:select

    /**
     * The database generated values.
     */
    // @part:Gen
    record CustomerGen(long id, @JdbcName("created") LocalDateTime createdDateTime) {
    }
    // @part:Gen

    /*
     * Define a SQL update to insert a row into the table.
     * The values of the 'id' and 'created' columns will be generated by the database.
     * To get those values back we define a record CustomerGen and add the @JdbcReturnGeneratedValues annotation
     */
    // @part:insert
    @JdbcUpdate("INSERT INTO db_customers (name, budge) VALUES (:name, :budge)")
    @JdbcReturnGeneratedValues
    CustomerGen insertCustomer(String name, @org.jspecify.annotations.Nullable Integer budge);
    // @part:insert

    /*
     * @return the number of delete rows (return value of executeUpdate)
     */
    // @part:delete
    @JdbcUpdate("DELETE FROM db_customers")
    int deleteCustomers();
    // @part:delete

    /*
     * @return the count(*) of all customers
     */
    // @part:countCustomers
    @JdbcSelect("SELECT COUNT(*) FROM db_customers")
    int countCustomers();
    // @part:countCustomers
}
// @part:class
