# SPDX-FileCopyrightText: 2025 kaumei.io
# SPDX-License-Identifier: Apache-2.0
name: Bug report
description: Report a reproducible problem in kaumei-jdbc
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug.

        Issues are used for concrete, actionable problems.
        If you are unsure whether this is a bug, please use Discussions first.

  - type: input
    id: version
    attributes:
      label: kaumei-jdbc version
      placeholder: e.g. 0.1.0
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: e.g. Java 21, PostgreSQL 16, Linux
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the problem clearly and concisely.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      description: Minimal steps or code to reproduce the problem.
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional notes
    validations:
      required: false
