-- SPDX-FileCopyrightText: 2025 kaumei.io
-- SPDX-License-Identifier: Apache-2.0
CREATE SCHEMA IF NOT EXISTS test;
SET
search_path TO test;

CREATE TABLE db_address (
    id     BIGSERIAL PRIMARY KEY,
    city   VARCHAR(100),
    street VARCHAR(100),
    length INT
);
CREATE TABLE db_customers (
    id      BIGSERIAL PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    budge   INTEGER,
    created TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP
);

-- @part:db_name_mapping
CREATE TABLE db_name_mapping (
    id            BIGSERIAL PRIMARY KEY,
    foo_bar       VARCHAR(100),
    one_two_three VARCHAR(100)
);
-- @part:db_name_mapping

CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');
CREATE TABLE db_types (
    id            BIGSERIAL PRIMARY KEY,
    col_bytea     BYTEA,
    col_boolean   BOOLEAN,
    col_char      CHAR(1),
    col_date      DATE,
    col_int       INT,
    col_number    NUMERIC(15, 5),
    col_mood      mood,
    col_text      TEXT,
    col_time      TIME(6),
    col_timestamp TIMESTAMP(6),
    col_varchar   VARCHAR(255),
    col_uuid      UUID
);


--
--CREATE TABLE person (
--    id          BIGSERIAL PRIMARY KEY,
--    name        VARCHAR(255) NOT NULL,
--    birth       DATE,
--    plz         INT,
--    city        VARCHAR(255),
--    uuid        UUID,
--    is_customer VARCHAR(3)
--);
--
--CREATE SEQUENCE IF NOT EXISTS misc_seq;
--CREATE TABLE misc (
--    col_blob       blob,
--    col_boolean    BOOLEAN,
--    col_char       CHAR,
--    col_text_large CLOB,
--    col_date       DATE,
--    col_int        INT,
--    col_number     NUMBER(15, 5),
--    col_text       TEXT,
--    col_time       TIME(6),
--    col_timestamp  TIMESTAMP(6),
--    col_varchar    VARCHAR(255)
--);
--
---- USERS table
--CREATE TABLE users (
--    id     BIGSERIAL PRIMARY KEY,
--    name   varchar(255), -- generated by trigger example.UsersSetNameTrigger
--    remark varchar(255)
--);
--CREATE TRIGGER user_name_default
--    BEFORE INSERT
--    ON USERS
--    FOR EACH ROW
--    CALL "io.kaumei.jdbc.examples.UsersSetNameTrigger";