-- SPDX-FileCopyrightText: 2025 kaumei.io
-- SPDX-License-Identifier: Apache-2.0

create table if not exists customers (
    id bigint generated by default as identity primary key,
    name varchar(50) not null unique
);

create table if not exists restaurants (
    id bigint generated by default as identity primary key,
    name varchar(50) not null unique,
    address varchar(255) not null,
    customer_id bigint not null,
    constraint fk_restaurants_customer foreign key (customer_id) references customers (id)
);

create table if not exists service_online_booking (
    id bigint primary key,
    enabled boolean not null,
    max_days_before integer not null,
    min_persons integer,
    need_phone_number boolean not null,
    constraint fk_booking_restaurant foreign key (id) references restaurants (id)
);

create table if not exists service_accounting (
    id bigint primary key,
    enabled boolean not null,
    constraint fk_accounting_restaurant foreign key (id) references restaurants (id)
);

create table if not exists service_delivery_integration (
    id bigint primary key,
    enabled boolean not null,
    uber_id varchar(100),
    lieferando_id varchar(100),
    custom varchar(100),
    constraint fk_delivery_restaurant foreign key (id) references restaurants (id)
);

create table if not exists service_feedback (
    id bigint primary key,
    enabled boolean not null,
    constraint fk_feedback_restaurant foreign key (id) references restaurants (id)
);

create table if not exists service_staff_scheduling (
    id bigint primary key,
    enabled boolean not null,
    constraint fk_staff_restaurant foreign key (id) references restaurants (id)
);
